### ISSUE TITLE
Ansible Redfish

### ISSUE THREAD

**Issue by CesarCastriote** [DMTF/Redfish-Ansible-Playbooks#14]

**Comment by mraineri** [comment]
@CesarCastriote is there a bug or a request you'd like to file?

**Comment by chen231133** [comment]
ansible [core 2.13.3] community.general 5.5.0
I can't collect disk and storage controller information when obtaining information about the Inspur NF5280 M5 server, the information is as follows."

        "storage_controller": {
            "entries": [],
            "ret": false
        },
        "disk": {
            "entries": [],
            "ret": false
        },

**Comment by mraineri** [comment]
Are you able to provide what's in your playbook? Is there other response info our output to help us decide where to poke next? Does the Inspur NF5280 M5 server even report storage information via Redfish?

**Comment by chen231133** [comment]
1. I tested on Huawei 2288H V5 2288H V6, works fine.
2.&nbsp;Does the Inspur NF5280 M5 server even report storage information via Redfish?
###Yes,&nbsp;Inspur NF5280 M5 server even report&nbsp;storage informiation via postman.
3. get_disk_inventory.yml&nbsp;
---
- hosts: myhosts
&nbsp; connection: local
&nbsp; name: Get disk inventory
&nbsp; gather_facts: False


&nbsp; vars:
&nbsp; &nbsp; ansible_python_interpreter: "/usr/bin/env python"
&nbsp; &nbsp; datatype: DiskInventory


&nbsp; tasks:


&nbsp; - name: Define output file
&nbsp; &nbsp; include_tasks: create_output_file.yml


&nbsp; - name: Get disk inventory
&nbsp; &nbsp; community.general.redfish_info:
&nbsp; &nbsp; &nbsp; category: Systems
&nbsp; &nbsp; &nbsp; command: GetDiskInventory
&nbsp; &nbsp; &nbsp; baseuri: "{{ baseuri }}"
&nbsp; &nbsp; &nbsp; username: "{{ username }}"
&nbsp; &nbsp; &nbsp; password: "{{ password }}"
&nbsp; &nbsp; register: result


&nbsp; - name: Copy results to output file
&nbsp; &nbsp; ansible.builtin.copy:
&nbsp; &nbsp; &nbsp; content: "{{ result | to_nice_json }}"
&nbsp; &nbsp; &nbsp; dest: "{{ template }}.json"
&nbsp;###get_storage_cont_inventory.yml###
---
- hosts: myhosts
&nbsp; connection: local
&nbsp; name: Get storage controller inventory
&nbsp; gather_facts: False


&nbsp; vars:
&nbsp; &nbsp; ansible_python_interpreter: "/usr/bin/env python"
&nbsp; &nbsp; datatype: StorageControllerInventory


&nbsp; tasks:


&nbsp; - name: Define output file
&nbsp; &nbsp; include_tasks: create_output_file.yml


&nbsp; - name: Get storage controller inventory
&nbsp; &nbsp; community.general.redfish_info:
&nbsp; &nbsp; &nbsp; category: Systems
&nbsp; &nbsp; &nbsp; command: GetStorageControllerInventory
&nbsp; &nbsp; &nbsp; baseuri: "{{ baseuri }}"
&nbsp; &nbsp; &nbsp; username: "{{ username }}"
&nbsp; &nbsp; &nbsp; password: "{{ password }}"
&nbsp; &nbsp; register: result


&nbsp; - name: Copy results to output file
&nbsp; &nbsp; ansible.builtin.copy:
&nbsp; &nbsp; &nbsp; content: "{{ result | to_nice_json }}"
&nbsp; &nbsp; &nbsp; dest: "{{ template }}.json"
&nbsp;


山里人?阿里?计算
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mike ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 上午9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DMTF/Redfish-Ansible-Playbooks] Ansible Redfish (Issue #14)





 
Are you able to provide what's in your playbook? Is there other response info our output to help us decide where to poke next? Does the Inspur NF5280 M5 server even report storage information via Redfish?

**Comment by chen231133** [comment]
1. I tested on Huawei 2288H V5 2288H V6, works fine
2. Does the Inspur NF5280 M5 server even report storage information via Redfish?
###Yes, it does. Inspur NF5280 M5 server reports storage informiation via postman.
3. get_disk_inventory.yml
---
- hosts: myhosts
  connection: local
  name: Get disk inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: DiskInventory

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get disk inventory
    community.general.redfish_info:
      category: Systems
      command: GetDiskInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"

###get_storage_cont_inventory.yml
---
- hosts: myhosts
  connection: local
  name: Get storage controller inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    datatype: StorageControllerInventory

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get storage controller inventory
    community.general.redfish_info:
      category: Systems
      command: GetStorageControllerInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"

**Comment by mraineri** [comment]
Can you show me how it's reported via Postman? Is it following the old "SimpleStorage" model or the more fleshed out "Storage" model? Do you have sample payloads that show how the "ComputerSystem" view is being modeled?

**Comment by mraineri** [comment]
Closing; no updates and it's unclear if the service is even behaving properly
