### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by donzef** [DMTF/Redfish-Ansible-Playbooks#9]
In the README.md, the last line of the "Redfish Ansible Modules"  paragraph points to [redfish_utils.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/redfish_utils.py) which is a broken link (404). 

I was trying to understand whether the Redfish Ansible modules mentioned in this repo were using the [DMTF Python Redfish Library](https://github.com/DMTF/python-redfish-library)

**Comment by billdodd** [comment]
Thanks for pointing out the broken links. The Redfish modules are now in https://github.com/ansible-collections/community.general
e.g. https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/redfish_utils.py

(And no, the Ansible modules do not use python-redfish-library.)

**Comment by mraineri** [comment]
@billdodd do we need to do anything else other than your README updates? If not, I think we can close this.

**Comment by billdodd** [comment]
> @billdodd do we need to do anything else other than your README updates? If not, I think we can close this.

Yes, we can close this one. I do want to also do some updates to the devel branch README to point to the modules and docs in community.general, but I'll do another issue for that.
